# Generated by Django 6.1 on 2026-09-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('update_balance', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('Loan', 'Loan'), ('Withdraw', 'Withdraw'), ('Deposite', 'Deposite')], max_length=100)),
                ('timespamp', models.DateTimeField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
