# Generated by Django 6.1 on 2026-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timespamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
