# Generated by Django 6.1 on 2026-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Withdraw', 'Withdraw'), ('Deposite', 'Deposite'), ('TransferMoney', 'TransferMoney')], max_length=100),
        ),
    ]
