# Generated by Django 6.1 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
